### ISSUE TITLE
Enable/tweak Garbage Collector

### ISSUE THREAD

**Issue by Abuk007** [CntoDev/tactical-tuesday-tours#11]
Garbage Collector (Editor -> Attributes -> Performance) can be used to remove dead bodies/destroyed vehicles when there is no player activity nearby for certain amount of time. Due to quick respawn nature bodies might pile up decreasing performance. Admin/Zeus activity should be reduced to absolute minimum.

**Comment by milivojm** [comment]
Addressed in 00a094cf891eb638e28bec115a21ec34a1da6dfc
