### ISSUE TITLE
Add "Dynamic Groups" to the scenario

### ISSUE THREAD

**Issue by Abuk007** [CntoDev/tactical-tuesday-tours#12]
This is an experimental suggestion.

Due to a very guerrilla nature of the scenario, it might be a good idea to add "Dynamic Groups"
https://community.bistudio.com/wiki/Dynamic_Groups

This will enable people to form groups with callsign of their choice instead of auto-generated "alpha x-y"

I'm not sure how compatible it is with ST Hud/Ace, but it might be worth a shot.

**Comment by milivojm** [comment]
Will try, sounds like a good idea.
