### ISSUE TITLE
state of the world not preserved

### ISSUE THREAD

**Issue by milivojm** [CntoDev/tactical-tuesday-tours#18]
State of the mission was reverted to default for unknown reason. Inventory and strategic map were set at zero hours. 

Test both on development and production server, reset after testing.

**Comment by Abuk007** [comment]
What was preserved: User assignment to each side.

**Comment by S7uk4** [comment]
Test on Dev server:
Moving objects from one crate to another & displaced vehicles were properly saved after ending the mission with #missions.

New issue: large green ammunition crates have Arsenal (2 arsenal options available in the scroll wheel menu).

**Comment by milivojm** [comment]
@Abuk007 are there any differences between dev and prod server? Because we didn't change a line of code.

**Comment by Abuk007** [comment]
Its the same hardware, same system, bandwidth, different user accounts.
Its using same server files, same mods. Same as production it has 1x HC running.

Difference is: you can add custom mods on top of it or override out native mods.
It also has a separate repository for purpose of hosting custom mods. It has its own server profile and server.cfg.

By default Dev server is fully accessible for SSgt, MMT, R&D and Training Branch managers (direct access to the remote desktop) and partially accessible for MMT and R&D members (missions FTP).

**Comment by milivojm** [comment]
We'll test over and over again. Hopefully that issue was a one off.

**Comment by milivojm** [comment]
@Abuk007 - if you have time today, please restart the production server (just Arma 3 server process) and then see if state is loaded. One flag should be seized by blufor.

**Comment by ItsRaykin** [comment]
Tested moving vehicles out of base, moving stuff around in crates, Basically did what you'd expect a player to do during the game. It all worked fine. Went out of game and back in to see if it got saved and it did.

**Comment by milivojm** [comment]
I will close this issue, after two tests by different testers. If the issue reappears, we'll open the issue again.
