### ISSUE TITLE
Mission uploaded to CNTR

### ISSUE THREAD

**Issue by Abuk007** [CntoDev/tactical-tuesday-tours#5]
So since our missions are auto-uploaded to CNTR upon mission end, we can use #missions to end it without saving to CNTR, however will it break save state of the mission?

**Comment by milivojm** [comment]
It will not break it, mission state is saved every 2 minutes on the server itself.

**Comment by milivojm** [comment]
Think we can close this one. You can freely use `#missions` at the end, nothing will be broken.
