### ISSUE TITLE
performance issues

### ISSUE THREAD

**Issue by milivojm** [CntoDev/tactical-tuesday-tours#6]
Players report stuttering, especially when players are not that localized. Some people think it's about AI vs AI.

**Comment by Abuk007** [comment]
Issue occurred at the same time for everyone (approx 1 hour into the mission). Micro-stutters every ~2 seconds for ~0.3 sec.

Fixed by going back to lobby and spawning in again or Arma restart.

**Comment by milivojm** [comment]
This one will be the hardest to fix, I'm afraid. I could try halving the number of AI.

**Comment by milivojm** [comment]
Removed QRF from INDFOR, turned `canTriggerDynamicSimulation false;` on all AI, removed 1 patrol from villages, turned on aggressive garbage collection.
